---
root: true
parserOptions:
  sourceType: module
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:react/jsx-runtime"
  - "plugin:react-hooks/recommended"
  - plugin:jsx-a11y/strict
  - "prettier"
env:
  browser: true
  node: false
  es2021: true
rules:
  no-console: "warn"
  react-hooks/exhaustive-deps:
    - "warn"
    - additionalHooks: "(useRecoilCallback|useRecoilTransaction_UNSTABLE)"
